directories = [
    "recon",
    "enum",
    "exploit",
    "password",
    "web",
    "network",
    "post-exploit",
    "forensics",
    "wireless",
    "rev",
    "privesc",
    "cloud",
    "containers",
    "osint",
    "audit",
    "remote",
]
